import localFont from "next/font/local";
import "./globals.css";
import NavBar from "../components/NavBar";
import Footer from "@/components/Footer";
// import { Provider } from "react-redux";
import Sidebar from "@/components/SideBar";
// import { store } from "../redux/store";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-screen flex" style={{background:"#f6f9fc"}}>
          <Sidebar />
          <div className="p-5 w-screen ps-20 pe-20">
            <NavBar />
            {children}
          </div>
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
